# Generated by flox-agent import — do not edit by hand.
# source: https://github.com/coreyhaines31/marketingskills @ 5b2c0007766c6a1cf1d53fd8fc73e979e0821022
{ buildAgentPlugin, fetchFromGitHub }:

buildAgentPlugin {
  name = "marketing-skills";
  version = "2.11.1";
  src = fetchFromGitHub {
    owner = "coreyhaines31";
    repo = "marketingskills";
    rev = "5b2c0007766c6a1cf1d53fd8fc73e979e0821022";
    hash = "sha256-x2dcZrwUMaGK4wHNQtE2TvPH5mBR474mW0Y5fQb19dw=";
  };
  sourceUrl = "https://github.com/coreyhaines31/marketingskills";

  manifest = {
    "$schema" = "https://agent-plugins.org/schemas/1.1.0/plugin.schema.json";
    author = {
      name = "Corey Haines";
    };
    description = "Marketing skills for AI agents — conversion optimization, copywriting, SEO, paid ads, ad creative, and growth";
    homepage = "https://github.com/coreyhaines31/marketingskills";
    license = "MIT";
    name = "marketing-skills";
    repository = "https://github.com/coreyhaines31/marketingskills";
    version = "2.11.1";
  };

  skills = {
    "ab-testing" = "skills/ab-testing";
    "ad-creative" = "skills/ad-creative";
    "ads" = "skills/ads";
    "ai-seo" = "skills/ai-seo";
    "analytics" = "skills/analytics";
    "aso" = "skills/aso";
    "attribution" = "skills/attribution";
    "churn-prevention" = "skills/churn-prevention";
    "co-marketing" = "skills/co-marketing";
    "cold-email" = "skills/cold-email";
    "community-marketing" = "skills/community-marketing";
    "competitor-profiling" = "skills/competitor-profiling";
    "competitors" = "skills/competitors";
    "content-strategy" = "skills/content-strategy";
    "copy-editing" = "skills/copy-editing";
    "copywriting" = "skills/copywriting";
    "cro" = "skills/cro";
    "customer-research" = "skills/customer-research";
    "directory-submissions" = "skills/directory-submissions";
    "emails" = "skills/emails";
    "events" = "skills/events";
    "free-tools" = "skills/free-tools";
    "image" = "skills/image";
    "influencer-marketing" = "skills/influencer-marketing";
    "launch" = "skills/launch";
    "lead-magnets" = "skills/lead-magnets";
    "marketing-council" = "skills/marketing-council";
    "marketing-ideas" = "skills/marketing-ideas";
    "marketing-loops" = "skills/marketing-loops";
    "marketing-plan" = "skills/marketing-plan";
    "marketing-psychology" = "skills/marketing-psychology";
    "offers" = "skills/offers";
    "onboarding" = "skills/onboarding";
    "paywalls" = "skills/paywalls";
    "popups" = "skills/popups";
    "pricing" = "skills/pricing";
    "product-marketing" = "skills/product-marketing";
    "programmatic-seo" = "skills/programmatic-seo";
    "prospecting" = "skills/prospecting";
    "public-relations" = "skills/public-relations";
    "referrals" = "skills/referrals";
    "revops" = "skills/revops";
    "sales-enablement" = "skills/sales-enablement";
    "schema" = "skills/schema";
    "seo-audit" = "skills/seo-audit";
    "signup" = "skills/signup";
    "site-architecture" = "skills/site-architecture";
    "sms" = "skills/sms";
    "social" = "skills/social";
    "video" = "skills/video";
  };

  meta = {
    description = "Marketing skills for AI agents — conversion optimization, copywriting, SEO, paid ads, ad creative, and growth";
    homepage = "https://github.com/coreyhaines31/marketingskills";
  };
}
