# Generated by agent-stacks import.
#
# Everything outside the custom markers is rewritten on every import, so
# changes there are lost. Everything between them is left alone.
{ buildAgentPlugin, pkgs }:

let
  source = builtins.fromJSON (builtins.readFile ./source.json);
  # BEGIN custom — kept as it is when this file is regenerated
  args = { };
  hooks = old: { };
  # END custom — anything outside these markers is overwritten
in
(buildAgentPlugin (source // args)).overrideAttrs hooks
