# Generated by flox-agent import — do not edit by hand.
# source: https://github.com/obra/superpowers @ b36e0829c6d0140e93cfef2ca599b1b07d4a7797
{ buildAgentPlugin, fetchFromGitHub }:

buildAgentPlugin {
  name = "superpowers";
  version = "6.3.0";
  src = fetchFromGitHub {
    owner = "obra";
    repo = "superpowers";
    rev = "b36e0829c6d0140e93cfef2ca599b1b07d4a7797";
    hash = "sha256-EsGNO0dULWf5Bx6bGrCv2kI2Z8aKH0kRvGiuN23wChQ=";
  };
  sourceUrl = "https://github.com/obra/superpowers";

  manifest = {
    "$schema" = "https://agent-plugins.org/schemas/1.1.0/plugin.schema.json";
    author = {
      email = "jesse@fsck.com";
      name = "Jesse Vincent";
    };
    description = "Core skills library for Claude Code: TDD, debugging, collaboration patterns, and proven techniques";
    homepage = "https://github.com/obra/superpowers";
    keywords = [
      "skills"
      "tdd"
      "debugging"
      "collaboration"
      "best-practices"
      "workflows"
    ];
    license = "MIT";
    name = "superpowers";
    repository = "https://github.com/obra/superpowers";
    version = "6.3.0";
  };

  skills = {
    "brainstorming" = "skills/brainstorming";
    "dispatching-parallel-agents" = "skills/dispatching-parallel-agents";
    "executing-plans" = "skills/executing-plans";
    "finishing-a-development-branch" = "skills/finishing-a-development-branch";
    "receiving-code-review" = "skills/receiving-code-review";
    "requesting-code-review" = "skills/requesting-code-review";
    "subagent-driven-development" = "skills/subagent-driven-development";
    "systematic-debugging" = "skills/systematic-debugging";
    "test-driven-development" = "skills/test-driven-development";
    "using-git-worktrees" = "skills/using-git-worktrees";
    "using-superpowers" = "skills/using-superpowers";
    "verification-before-completion" = "skills/verification-before-completion";
    "writing-plans" = "skills/writing-plans";
    "writing-skills" = "skills/writing-skills";
  };

  meta = {
    description = "Core skills library for Claude Code: TDD, debugging, collaboration patterns, and proven techniques";
    homepage = "https://github.com/obra/superpowers";
  };
}
