# Generated by flox-agent import — do not edit by hand.
# source: https://github.com/supabase/agent-skills @ 8331f910845103c08d51f6ca1d86ebb7d1f745e3
{ buildAgentPlugin, fetchFromGitHub }:

buildAgentPlugin {
  name = "agent-skills";
  version = "0-unstable-2026-08-12";
  src = fetchFromGitHub {
    owner = "supabase";
    repo = "agent-skills";
    rev = "8331f910845103c08d51f6ca1d86ebb7d1f745e3";
    hash = "sha256-cj+ng8dR/S10o5FmloOQRUohhRskON8Sx7xurEMqdfg=";
  };
  sourceUrl = "https://github.com/supabase/agent-skills";

  manifest = {
    "$schema" = "https://agent-plugins.org/schemas/1.1.0/plugin.schema.json";
    name = "agent-skills";
  };

  skills = {
    "supabase" = "skills/supabase";
    "supabase-postgres-best-practices" = "skills/supabase-postgres-best-practices";
  };

  meta = {
    description = "Agent plugin imported from https://github.com/supabase/agent-skills";
    homepage = "https://github.com/supabase/agent-skills";
  };
}
