# Generated by flox-agent import — do not edit by hand.
# source: https://github.com/vercel-labs/agent-browser @ 219c47a9dab1776f320d11e66ce934fd239b2cb7
{ buildAgentPlugin, fetchFromGitHub }:

buildAgentPlugin {
  name = "agent-browser";
  version = "0-unstable-2026-09-07";
  src = fetchFromGitHub {
    owner = "vercel-labs";
    repo = "agent-browser";
    rev = "219c47a9dab1776f320d11e66ce934fd239b2cb7";
    hash = "sha256-AOKO04e8j35XG+xPhpLVd1U0l6sI+ujBY15zUuXvATk=";
  };
  sourceUrl = "https://github.com/vercel-labs/agent-browser";

  manifest = {
    "$schema" = "https://agent-plugins.org/schemas/1.1.0/plugin.schema.json";
    name = "agent-browser";
  };

  skills = {
    "agent-browser" = "skills/agent-browser";
    "agentcore" = "skill-data/agentcore";
    "core" = "skill-data/core";
    "derive-client" = "skill-data/derive-client";
    "dogfood" = "skill-data/dogfood";
    "electron" = "skill-data/electron";
    "protected-vercel-deployments" = "skill-data/protected-vercel-deployments";
    "slack" = "skill-data/slack";
    "vercel-sandbox" = "skill-data/vercel-sandbox";
    "webmcp-gen" = "skill-data/webmcp-gen";
  };

  meta = {
    description = "Agent plugin imported from https://github.com/vercel-labs/agent-browser";
    homepage = "https://github.com/vercel-labs/agent-browser";
  };
}
