# Generated by flox-agent import — do not edit by hand.
# source: https://github.com/nextlevelbuilder/ui-ux-pro-max-skill @ 4aad0584d92131626b16d4ff4d77f0455385013c
{ buildAgentPlugin, fetchFromGitHub }:

buildAgentPlugin {
  name = "ui-ux-pro-max";
  version = "2.13.0";
  src = fetchFromGitHub {
    owner = "nextlevelbuilder";
    repo = "ui-ux-pro-max-skill";
    rev = "4aad0584d92131626b16d4ff4d77f0455385013c";
    hash = "sha256-W04fYlu0pRIz+fW8jFVz33TRxe2rEi2Nrcw+XoZo/jA=";
  };
  sourceUrl = "https://github.com/nextlevelbuilder/ui-ux-pro-max-skill";

  manifest = {
    "$schema" = "https://agent-plugins.org/schemas/1.1.0/plugin.schema.json";
    author = {
      name = "nextlevelbuilder";
    };
    description = "UI/UX design intelligence. Searchable local database with 79 styles, 192 palettes, 74 font pairings, 25 charts, and 22 stacks (React, Next.js, Vue, Nuxt.js, Nuxt UI, Svelte, Astro, SwiftUI, React Native, Flutter, Tailwind, shadcn/ui, Jetpack Compose, Angular, Laravel, JavaFX, WPF, WinUI, Avalonia, Uno Platform, UWP, Three.js). Use when designing, building, or reviewing UI: pages, components, color schemes, typography, layout, accessibility, animation, or data visualization.";
    keywords = [
      "ui"
      "ux"
      "design"
      "styles"
      "typography"
      "color-palette"
      "accessibility"
      "charts"
      "components"
    ];
    license = "MIT";
    name = "ui-ux-pro-max";
    version = "2.13.0";
  };

  skills = {
    "banner-design" = "cli/assets/skills/banner-design";
    "brand" = "cli/assets/skills/brand";
    "design" = "cli/assets/skills/design";
    "design-system" = "cli/assets/skills/design-system";
    "slides" = "cli/assets/skills/slides";
    "ui-styling" = "cli/assets/skills/ui-styling";
  };

  meta = {
    description = "UI/UX design intelligence";
    homepage = "https://github.com/nextlevelbuilder/ui-ux-pro-max-skill";
  };
}
