# Generated by flox-agent import — do not edit by hand.
# source: https://github.com/juliusbrussee/caveman @ 15581d14007fd01fb3f132016741962f34936ca2
{ buildAgentPlugin, fetchFromGitHub }:

buildAgentPlugin {
  name = "caveman";
  version = "0-unstable-2026-09-07";
  src = fetchFromGitHub {
    owner = "juliusbrussee";
    repo = "caveman";
    rev = "15581d14007fd01fb3f132016741962f34936ca2";
    hash = "sha256-GuCK3oy0DsMOQq7gHjIY/aeaukJcTvelfg+tp7R7Du4=";
  };
  sourceUrl = "https://github.com/juliusbrussee/caveman";

  manifest = {
    "$schema" = "https://agent-plugins.org/schemas/1.1.0/plugin.schema.json";
    author = {
      name = "Julius Brussee";
      url = "https://github.com/JuliusBrussee";
    };
    description = "Ultra-compressed communication mode. Cuts 65% of output tokens against an unprompted baseline (measured) while keeping full technical accuracy by speaking like a caveman.";
    name = "caveman";
  };

  skills = {
    "cavecrew" = "skills/cavecrew";
  };

  meta = {
    description = "Ultra-compressed communication mode";
    homepage = "https://github.com/juliusbrussee/caveman";
  };
}
