# Generated by flox-agent import — do not edit by hand.
# source: https://github.com/vercel-labs/skills @ 1682051d48c34f5eb135e6475c1a965dce05e820
{ buildAgentPlugin, fetchFromGitHub }:

buildAgentPlugin {
  name = "skills";
  version = "0-unstable-2026-09-06";
  src = fetchFromGitHub {
    owner = "vercel-labs";
    repo = "skills";
    rev = "1682051d48c34f5eb135e6475c1a965dce05e820";
    hash = "sha256-0BmVByaPFacM4Tncrs8Kq56MqDyDWrKCJmQhqEolTOs=";
  };
  sourceUrl = "https://github.com/vercel-labs/skills";

  manifest = {
    "$schema" = "https://agent-plugins.org/schemas/1.1.0/plugin.schema.json";
    name = "skills";
  };

  skills = {
    "find-skills" = "skills/find-skills";
  };

  meta = {
    description = "Agent plugin imported from https://github.com/vercel-labs/skills";
    homepage = "https://github.com/vercel-labs/skills";
  };
}
