# Generated by flox-agent import — do not edit by hand.
# source: https://github.com/mattpocock/skills @ 3cca18b368ae95cdbdebbff572ccafa662551015
{ buildAgentPlugin, fetchFromGitHub }:

buildAgentPlugin {
  name = "mattpocock-skills";
  version = "1.2.3";
  src = fetchFromGitHub {
    owner = "mattpocock";
    repo = "skills";
    rev = "3cca18b368ae95cdbdebbff572ccafa662551015";
    hash = "sha256-dF5i37jHnqfcXD1IRSVzSSm/pfCYSUmOsEhhs5Zx340=";
  };
  sourceUrl = "https://github.com/mattpocock/skills";

  manifest = {
    "$schema" = "https://agent-plugins.org/schemas/1.1.0/plugin.schema.json";
    author = {
      name = "Matt Pocock";
      url = "https://www.aihero.dev";
    };
    description = "Matt Pocock's agent skills for real engineering: grilling, spec/ticket flows, TDD, code review, domain modelling and more. Plug-and-play, not vibe coding.";
    homepage = "https://www.aihero.dev/s/skills-newsletter";
    keywords = [
      "engineering"
      "skills"
      "tdd"
      "code-review"
      "grilling"
      "domain-modeling"
      "productivity"
    ];
    license = "MIT";
    name = "mattpocock-skills";
    repository = "https://github.com/mattpocock/skills";
    version = "1.2.3";
  };

  skills = {
    "ask-matt" = "skills/engineering/ask-matt";
    "claude-handoff" = "skills/in-progress/claude-handoff";
    "code-review" = "skills/engineering/code-review";
    "codebase-design" = "skills/engineering/codebase-design";
    "diagnosing-bugs" = "skills/engineering/diagnosing-bugs";
    "domain-modeling" = "skills/engineering/domain-modeling";
    "git-guardrails-claude-code" = "skills/misc/git-guardrails-claude-code";
    "grill-me" = "skills/productivity/grill-me";
    "grill-with-docs" = "skills/engineering/grill-with-docs";
    "grilling" = "skills/productivity/grilling";
    "handoff" = "skills/productivity/handoff";
    "implement" = "skills/engineering/implement";
    "implement-spec" = "skills/in-progress/implement-spec";
    "improve-codebase-architecture" = "skills/engineering/improve-codebase-architecture";
    "loop-me" = "skills/in-progress/loop-me";
    "migrate-to-shoehorn" = "skills/misc/migrate-to-shoehorn";
    "prototype" = "skills/engineering/prototype";
    "research" = "skills/engineering/research";
    "resolving-merge-conflicts" = "skills/engineering/resolving-merge-conflicts";
    "retro" = "skills/in-progress/retro";
    "scaffold-exercises" = "skills/misc/scaffold-exercises";
    "setup-matt-pocock-skills" = "skills/engineering/setup-matt-pocock-skills";
    "setup-pre-commit" = "skills/misc/setup-pre-commit";
    "setup-ts-deep-modules" = "skills/in-progress/setup-ts-deep-modules";
    "tdd" = "skills/engineering/tdd";
    "teach" = "skills/productivity/teach";
    "to-questionnaire" = "skills/productivity/to-questionnaire";
    "to-spec" = "skills/engineering/to-spec";
    "to-tickets" = "skills/engineering/to-tickets";
    "triage" = "skills/engineering/triage";
    "wait-what" = "skills/productivity/wait-what";
    "wayfinder" = "skills/engineering/wayfinder";
    "wizard" = "skills/engineering/wizard";
    "writing-beats" = "skills/in-progress/writing-beats";
    "writing-for-agents" = "skills/productivity/writing-for-agents";
    "writing-fragments" = "skills/in-progress/writing-fragments";
    "writing-shape" = "skills/in-progress/writing-shape";
  };

  meta = {
    description = "Matt Pocock's agent skills for real engineering: grilling, spec/ticket flows, TDD, code review, domain modelling and more";
    homepage = "https://github.com/mattpocock/skills";
  };
}
