# Generated by flox-agent import — do not edit by hand.
# source: https://github.com/shadcn/ui @ 5c7072da672b0048bc6771e3204063a2537df91a
{ buildAgentPlugin, fetchFromGitHub }:

buildAgentPlugin {
  name = "ui";
  version = "0-unstable-2026-09-06";
  src = fetchFromGitHub {
    owner = "shadcn";
    repo = "ui";
    rev = "5c7072da672b0048bc6771e3204063a2537df91a";
    hash = "sha256-c697iZWvY84lhgUpSo3OEQUZWnSe3J147P7Lr5GzHLw=";
  };
  sourceUrl = "https://github.com/shadcn/ui";

  manifest = {
    "$schema" = "https://agent-plugins.org/schemas/1.1.0/plugin.schema.json";
    name = "ui";
  };

  skills = {
    "migrate-radix-to-base" = "skills/migrate-radix-to-base";
    "shadcn" = "skills/shadcn";
  };

  meta = {
    description = "Agent plugin imported from https://github.com/shadcn/ui";
    homepage = "https://github.com/shadcn/ui";
  };
}
